// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqKzYTE38iw_7SWqgDAaSJE93IpI4e2Vw',
    appId: '1:455680836900:web:d4396784a7eb02c66d9fb1',
    messagingSenderId: '455680836900',
    projectId: 'streak-couch-app',
    authDomain: 'streak-couch-app.firebaseapp.com',
    storageBucket: 'streak-couch-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC31JtPI9jRjeE5153ewUOy-gjdga4kP88',
    appId: '1:455680836900:android:681effde9c88c9096d9fb1',
    messagingSenderId: '455680836900',
    projectId: 'streak-couch-app',
    storageBucket: 'streak-couch-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo7laZ7af4RJAS-l-d9HHbfVgYwAgB1Hg',
    appId: '1:455680836900:ios:cab0e859ee98a2476d9fb1',
    messagingSenderId: '455680836900',
    projectId: 'streak-couch-app',
    storageBucket: 'streak-couch-app.firebasestorage.app',
    iosBundleId: 'com.example.od1',
  );
}
